server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}

# Cache
spring.cache.type=caffeine

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Logging
logging.level.com.ingestion.pe=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=DEBUG

# Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.bootstrap-servers=${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=ms-core-local-skip-10
spring.kafka.consumer.auto-offset-reset=latest
kafka.group.id=ms-core-local-skip-10

# Topics (Development topics used in local to avoid polluting prod)
kafka.topic.position=gps-tcp-position-dev
kafka.topic.devices=gps-tcp-devices-dev
kafka.topic.websocket=gps-websocket-dev
kafka.topic.notifications=gps-notifications-dev
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6378
spring.data.redis.timeout=2000
spring.data.redis.database=2

# Security Params
security.authentication-type=BEARER
jwt.expiration.s=60480000000
jwt.refresh.expiration.s=60480000000
